# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "kobylynskyi"
    reviewers:
      - "kobylynskyi"

  - package-ecosystem: "gradle"
    directory: "/plugins/gradle/graphql-java-codegen-gradle-plugin"
    schedule:
      interval: "daily"
    assignees:
      - "kobylynskyi"
    reviewers:
      - "kobylynskyi"

  - package-ecosystem: "gradle"
    directory: "/plugins/gradle/example-server"
    schedule:
      interval: "daily"
    assignees:
      - "kobylynskyi"
    reviewers:
      - "kobylynskyi"

  - package-ecosystem: "gradle"
    directory: "/plugins/gradle/example-client"
    schedule:
      interval: "daily"
    assignees:
      - "kobylynskyi"
    reviewers:
      - "kobylynskyi"

  - package-ecosystem: "maven"
    directory: "/plugins/maven/graphql-java-codegen-maven-plugin"
    schedule:
      interval: "daily"
    assignees:
      - "kobylynskyi"
    reviewers:
      - "kobylynskyi"

  - package-ecosystem: "maven"
    directory: "/plugins/maven/example-server"
    schedule:
      interval: "daily"
    assignees:
      - "kobylynskyi"
    reviewers:
      - "kobylynskyi"

  - package-ecosystem: "maven"
    directory: "/plugins/maven/example-client"
    schedule:
      interval: "daily"
    assignees:
      - "kobylynskyi"
    reviewers:
      - "kobylynskyi"
